---
- name: Accept 80/tcp (http)
  iptables:
    chain: INPUT
    ip_version: "{{ item }}"
    protocol: tcp
    ctstate: NEW
    destination_port: '80'
    jump: ACCEPT
  with_items: ['ipv4', 'ipv6']

- name: Accept 443/tcp (https)
  iptables:
    chain: INPUT
    ip_version: "{{ item }}"
    protocol: tcp
    ctstate: NEW
    destination_port: '443'
    jump: ACCEPT
  with_items: ['ipv4', 'ipv6']

- name: Save iptables rules to file
  shell: "service ip{{ item }}tables save"
  args:
    warn: false
  with_items: ['', '6']
