all:
  children:
    conoha:
      hosts:
        migration:
          ansible_host: 150.95.138.120
          ansible_port: 7
    aws:
      hosts:
        passportctl:
          ansible_host: passportcontrol.net
          ansible_port: 22