all:
  children:
    conoha:
      hosts:
        trijn:
          ansible_host: trijn.tyo.yuriko.co.nz
          ansible_port: 7
    aws:
      hosts:
        passportctl:
          ansible_host: passportcontrol.net
          ansible_port: 22