all:
  children:
    conoha:
      hosts:
        trijn: # Production
          ansible_host: trijn.tyo.yuriko.co.nz
          ansible_port: 7
        nijntje: # Develop
          ansible_host: nijntje.tyo.yuriko.co.nz
          ansible_port: 7
