- hosts: conoha
  become: yes
  gather_facts: no
  user: ansible
  tasks:
    - name: Install admin tools
      yum:
        name:
          - wget
          - yum-cron
          - audit
          - time
          - tree
          - abrt
          - abrt-cli
          - sg3_utils
          - git
          - rsync   # sync with old server
          - epel-release
          - chrony
          - bash-completion
          #- mtr
          #- python3-pip

    - name: Install admin tools (EPEL)
      yum:
        name:
          - pv
          - sl

    - block:
      - name: Install screenfetch 1/2
        yum:
          name: pciutils # for lspci
      - name: Install screenfetch 2/2
        get_url:
          url: https://raw.githubusercontent.com/KittyKatt/screenFetch/master/screenfetch-dev
          checksum: 'sha256:a411a19ad990fa3d7ac1959991471b35830a137741a364470e07781629cd15c4'
          owner: root
          group: root
          mode: 0755
          dest: /usr/local/bin/screenfetch
