- hosts: conoha
  become: yes
  gather_facts: no

  tasks:
    - name: Start chronyd
      service: name=chronyd state=started enabled=yes

    - name: Start abrtd
      service: name=abrtd state=started enabled=yes

    - name: start yum-cron
      service: name=yum-cron state=started enabled=yes
