- hosts: conoha
  become: yes
  gather_facts: no

  tasks:
    - name: Start serial console
      service: name=serial-getty@ttyS0.service state=started enabled=yes

    - name: Start chronyd
      service: name=chronyd state=started enabled=yes

    - name: Start abrtd
      service: name=abrtd state=started enabled=yes

    - name: Start crond
      service: name=crond state=started enabled=yes

    - name: Keep Old Log 52 Weeks with Compressed
      lineinfile:
        dest: /etc/logrotate.conf
        regexp: "{{ item.regexp }}"
        line: "{{ item.line }}"
        backup: yes
        state: present
      with_items:
        - regexp: '#compress'
          line: 'compress'
        - regexp: 'rotate 4'
          line: 'rotate 52'

    - name: Start sshd
      service: name=sshd state=started enabled=yes

    - name: Place sshd Configuration file
      template:
        src: sshd_config.j2
        dest: /etc/ssh/sshd_config
        owner: root
        group: root
        mode: 0600
      register: template_result

    - name: Apply sshd Configuration
      service: name=sshd state=restarted
      when: template_result is changed
