- hosts: localhost
  connection: local
  become: no
  gather_facts: no

  tasks:
    - name: Check DNS Record ConoHa
      set_fact:
        result: "{{ lookup('dig', item.record, 'qtype='+item.type)}}"
      changed_when: result != item.value
      with_items:
        - record: 'yuriko.co.nz.'
          value: '150.95.138.120'
          type: 'A'
        - record: 'yuriko.co.nz.'
          value: '2400:8500:1302:821:150:95:138:120'
          type: 'AAAA'
        - record: 'trijn.tyo.yuriko.co.nz.'
          value: '150.95.138.120'
          type: 'A'
        - record: 'trijn.tyo.yuriko.co.nz.'
          value: '2400:8500:1302:821:150:95:138:120'
          type: 'AAAA'
        - record: '150.95.138.120'
          value: 'trijn.tyo.yuriko.co.nz.'
          type: 'PTR'
        - record: '2400:8500:1302:821:150:95:138:120'
          value: 'trijn.tyo.yuriko.co.nz.'
          type: 'PTR'

        - record: 'ipv6.yuriko.co.nz.'
          value: '2400:8500:1302:821:150:95:138:120'
          type: 'AAAA'

        - record: 'openvpn.yuriko.co.nz.'
          value: 'trijn.tyo.yuriko.co.nz.'
          type: 'CNAME'
        - record: 'ipsec.yuriko.co.nz.'
          value: 'trijn.tyo.yuriko.co.nz.'
          type: 'CNAME'
        - record: 'mail.yuriko.co.nz.'
          value: 'trijn.tyo.yuriko.co.nz.'
          type: 'CNAME'
        - record: 'search.yuriko.co.nz.'
          value: 'trijn.tyo.yuriko.co.nz.'
          type: 'CNAME'
        - record: 'www.yuriko.co.nz.'
          value: 'trijn.tyo.yuriko.co.nz.'
          type: 'CNAME'
        - record: 'bfv.yuriko.co.nz.'
          value: 'trijn.tyo.yuriko.co.nz.'
          type: 'CNAME'

        - record: 'yuriko.co.nz.'
          value: '10 trijn.tyo.yuriko.co.nz.'
          type: 'MX'

        - record: 'yuriko.co.nz.'
          value: '128 issue "letsencrypt.org"'
          type: 'CAA'
        - record: 'yuriko.co.nz.'
          value: 'v=spf1 a mx a:trijn.tyo.yuriko.co.nz -all'
          type: 'TXT'
        - record: '_dmarc.yuriko.co.nz.'
          value: 'v=DMARC1; p=quarantine; rua=mailto:dmarc@yuriko.co.nz; ruf=mailto:dmarc@yuriko.co.nz; adkim=s; aspf=s'
          type: 'TXT'
        - record: 'dkim._domainkey.yuriko.co.nz.'
          value: 'v=DKIM1; k=rsa; p=MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQC7HOkHR5SFmi2omSnW/XhsBK1TEkuAIOF5QYOPzDYd2Oq4O8bsg9SzPubdsFGSAG60kT/2FK88VPOCRn6bbvfAMperhba2yfFHQE6Qc+o8Em+9ZS8fvoRgzaAXRemJwTTIZ/wL2PmwT5PqUOx/SxeFkQSmlMXxA9SLb/D+gH9y6QIDAQAB'
          type: 'TXT'
        - record: 'trijn.tyo.yuriko.co.nz.'
          value: 'v=spf1 a:trijn.tyo.yuriko.co.nz ~all'
          type: 'TXT'
        - record: '_dmarc.trijn.tyo.yuriko.co.nz.'
          value: 'v=DMARC1; p=quarantine; rua=mailto:dmarc@yuriko.co.nz; ruf=mailto:dmarc@yuriko.co.nz'
          type: 'TXT'

    - name: Check DNS Record (MyDNS)
      set_fact:
        result: "{{ lookup('dig', item.record, 'qtype='+item.type)}}"
      changed_when: result != item.value
      with_items:
        - record: 'ichikawayukko.mydns.jp.'
          value: '150.95.138.120'
          type: 'A'
        - record: 'ichikawayukko.mydns.jp.'
          value: '2400:8500:1302:821:150:95:138:120'
          type: 'AAAA'
