- hosts: conoha
  become: yes
  gather_facts: no

  tasks:
    - name: Activate SElinux
      selinux: policy=targeted state=enforcing

    - name: Install semanage
      yum:
        name: policycoreutils-python