---
- name: Enable CentOS Vault repository
  yum_repository:
    file: CentOS-Vault
    name: C7.9.2009-{{ item.name }}
    description: CentOS-7.9.2009 - {{ item.description }}
    baseurl: http://vault.centos.org/7.9.2009/{{ item.url }}/$basearch/
    gpgkey: file:///etc/pki/rpm-gpg/RPM-GPG-KEY-CentOS-7
    gpgcheck: yes
    enabled: yes
  with_items:
    - name: 'base'
      description: 'Base'
      url: 'os'
    - name: 'updates'
      description: 'Updates'
      url: 'updates'
    - name: 'extras'
      description: 'Extras'
      url: 'extras'

- name: Disable CentOS Base repository
  yum_repository:
    file: CentOS-Base
    name: "{{ item.name }}"
    description: CentOS-$releasever - {{ item.description }}
    mirrorlist: http://mirrorlist.centos.org/?release=$releasever&arch=$basearch&repo={{ item.repo }}&infra=$infra
    gpgkey: file:///etc/pki/rpm-gpg/RPM-GPG-KEY-CentOS-7
    gpgcheck: yes
    enabled: no
  with_items:
    - name: 'base'
      description: 'Base'
      repo: 'os'
    - name: 'updates'
      description: 'Updates'
      repo: 'updates'
    - name: 'extras'
      description: 'Extras'
      repo: 'extras'

- name: Change EoL EPEL baseurl
  yum_repository:
    file: epel
    name: epel
    description: Extra Packages for Enterprise Linux 7 - $basearch
    baseurl: https://archives.fedoraproject.org/pub/archive/epel/7.9/$basearch
    gpgkey: file:///etc/pki/rpm-gpg/RPM-GPG-KEY-EPEL-7
    gpgcheck: yes
    enabled: yes
    failovermethod: priority
