# All filesystem configurations are set by CentOS installer.
# So this playbook just check that configuration is correct.

# Layout:
# | /dev/vda 100GiB GPT                                                                                          |
# | /dev/vda1 BIOS 2MiB | /dev/vda2 /boot 2GiB ext4 | /dev/vda3 LVM PV 97.6GiB                                   |
# |                                                 | LVM VG centos                                              |
# |                                                 | LVM LV root 80GiB | LVM LV swap 8GiB | FREE (for snapshot) |

- hosts: conoha
  become: yes
  gather_facts: no

  tasks:
    - name: Assert BIOS partition existence
      parted:
        device: /dev/vda
        label: gpt
        number: 1
        flags: [ bios_grub ]
        part_start: 1MiB
        part_end: 3MiB
        part_type: primary
        state: info

    - name: Assert boot partition existence
      parted:
        device: /dev/vda
        label: gpt
        number: 2
        flags: [ ]
        part_start: 3MiB
        part_end: 2051MiB
        part_type: primary
        state: info

    - name: Assert LVM physical partition existence
      parted:
        device: /dev/vda
        label: gpt
        number: 3
        flags: [ lvm ]
        part_start: 2051MiB
        part_end: 102043MiB
        part_type: primary
        state: info

    - name: LVM centos VolumeGroup existence
      lvg:
        vg: centos
        pvs: /dev/vda3
        pesize: 4M
        state: present

    - name: LVM root LogicalVolume existence
      lvol:
        active: yes
        lv: root
        size: 80g
        vg: centos
        state: present

    - name: LVM swap LogicalVolume existence
      lvol:
        active: yes
        lv: swap
        size: 8g
        vg: centos
        state: present

    - name: root filesystem is ext4 format
      filesystem:
        dev: /dev/mapper/centos-root
        fstype: ext4

    - name: swap filesystem is swap format
      filesystem:
        dev: /dev/mapper/centos-swap
        fstype: swap

    - name: boot filesystem is ext4 format
      filesystem:
        dev: /dev/vda2
        fstype: ext4
