---
- name: Accept 25/tcp (smtp)
  iptables:
    chain: INPUT
    ip_version: "{{ item }}"
    protocol: tcp
    ctstate: NEW
    destination_port: '25'
    jump: ACCEPT
  with_items: ['ipv4', 'ipv6']

- name: Accept 587/tcp (submission)
  iptables:
    chain: INPUT
    ip_version: "{{ item }}"
    protocol: tcp
    ctstate: NEW
    destination_port: '587'
    jump: ACCEPT
  with_items: ['ipv4', 'ipv6']

- name: Accept 143/tcp (imap)
  iptables:
    chain: INPUT
    ip_version: "{{ item }}"
    protocol: tcp
    ctstate: NEW
    destination_port: '143'
    jump: ACCEPT
  with_items: ['ipv4', 'ipv6']

- name: Save iptables rules to file
  shell: "service ip{{ item }}tables save"
  args:
    warn: false
  with_items: ['', '6']
