---
- name: Accept 1194/udp (openvpn)
  iptables:
    chain: INPUT
    ip_version: "{{ item }}"
    protocol: udp
    destination_port: '1194'
    jump: ACCEPT
  with_items: ['ipv4', 'ipv6']

- name: Save iptables rules to file
  shell: "service ip{{ item }}tables save"
  args:
    warn: false
  with_items: ['', '6']
